### ISSUE TITLE
[BUG] ElevenClock OVER Screen Saver

### ISSUE THREAD

**Issue by RandyJae** [marticliment/ElevenClock#1227]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

With the Screen Saver Active, ElevenClock stil shows.

As per the FAQ, I have set the clock settings to 'hide the clock in fullscreen move'. Still shows when screen saver active.

### Steps to reproduce the issue

Wait for screen saver to activate

### ElevenClock Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.010970830917358398 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 4.2.2 (v4.22) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🟠 Monitor blacklisted!
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1400, 554, 200, 46)
🔵 Full screen rect:  (800, 0, 1600, 600)
🔵 Using automatic font color
🔵 Font families   : []
🔵 Custom font     : Times NR ElevenClock,26,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular
🔵 Font size: 26.0
🔵 Language file up-to-date
🟡 Custom loaded date time format (clock 1): %#I:%M
🟢 Loaded clocks in 0.5806722640991211
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, DisableNotifications:False
🔵 Restart loop: 1
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to True
🟢 Loaded everything in 2.4652419090270996
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 208, in setSettings

🔴   File ".\tools.py", line 208, in setSettings

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 Note this traceback was caught by reporter and has been added to the log (Internal C++ object (Clock) already deleted.)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 208, in setSettings

🔴   File ".\tools.py", line 208, in setSettings

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 Note this traceback was caught by reporter and has been added to the log (Internal C++ object (Clock) already deleted.)
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 208, in setSettings

🔴   File ".\tools.py", line 208, in setSettings

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 Note this traceback was caught by reporter and has been added to the log (Internal C++ object (Clock) already deleted.)
🟡 loadTimeFormat function has not been defined yet!
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 242, in setSettingsValue

🔴   File ".\tools.py", line 242, in setSettingsValue

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 Note this traceback was caught by reporter and has been added to the log (Internal C++ object (Clock) already deleted.)
🟠 Unable to retrieve latest announcement
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 643, in http_error_default

🔴   File "urllib\request.py", line 643, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 
During handling of the above exception, another exception occurred:


🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 557, in error

🔴   File "urllib\request.py", line 557, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 749, in http_error_302

🔴   File "urllib\request.py", line 749, in http_error_302

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 643, in http_error_default

🔴   File "urllib\request.py", line 643, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 Note this traceback was caught by reporter and has been added to the log (HTTP Error 502: Bad Gateway)
🔵 Showing tooltip
🔵 Long date string: dddd, MMMM d, yyyy
🟢 Specific clock settings for clock clock0_monSAMSUNG missing, generating one...
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 331, in openClockSettings

🔴   File ".\tools.py", line 331, in openClockSettings

🔴 KeyError: 'clock0_monSAMSUNG'

🔴 KeyError: 'clock0_monSAMSUNG'

🔴 
During handling of the above exception, another exception occurred:


🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 208, in setSettings

🔴   File ".\tools.py", line 208, in setSettings

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 Note this traceback was caught by reporter and has been added to the log (Internal C++ object (Clock) already deleted.)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 331, in openClockSettings

🔴   File ".\tools.py", line 331, in openClockSettings

🔴 KeyError: 'clock0_monSAMSUNG'

🔴 KeyError: 'clock0_monSAMSUNG'

🔴 
During handling of the above exception, another exception occurred:


🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 208, in setSettings

🔴   File ".\tools.py", line 208, in setSettings

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 Note this traceback was caught by reporter and has been added to the log (Internal C++ object (Clock) already deleted.)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 331, in openClockSettings

🔴   File ".\tools.py", line 331, in openClockSettings

🔴 KeyError: 'clock0_monSAMSUNG'

🔴 KeyError: 'clock0_monSAMSUNG'

🔴 
During handling of the above exception, another exception occurred:


🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 208, in setSettings

🔴   File ".\tools.py", line 208, in setSettings

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 Note this traceback was caught by reporter and has been added to the log (Internal C++ object (Clock) already deleted.)
🔵 Loading settings window with ID=clock0_monSAMSUNG
clock0_monET1523L-8UWA
clock0_monSAMSUNG
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 208, in setSettings

🔴   File ".\tools.py", line 208, in setSettings

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 Note this traceback was caught by reporter and has been added to the log (Internal C++ object (Clock) already deleted.)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 208, in setSettings

🔴   File ".\tools.py", line 208, in setSettings

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 Note this traceback was caught by reporter and has been added to the log (Internal C++ object (Clock) already deleted.)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 208, in setSettings

🔴   File ".\tools.py", line 208, in setSettings

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 Note this traceback was caught by reporter and has been added to the log (Internal C++ object (Clock) already deleted.)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 208, in setSettings

🔴   File ".\tools.py", line 208, in setSettings

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 Note this traceback was caught by reporter and has been added to the log (Internal C++ object (Clock) already deleted.)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 208, in setSettings

🔴   File ".\tools.py", line 208, in setSettings

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 Note this traceback was caught by reporter and has been added to the log (Internal C++ object (Clock) already deleted.)
🟠 Unable to retrieve latest announcement
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 643, in http_error_default

🔴   File "urllib\request.py", line 643, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 
During handling of the above exception, another exception occurred:


🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 557, in error

🔴   File "urllib\request.py", line 557, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 749, in http_error_302

🔴   File "urllib\request.py", line 749, in http_error_302

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 643, in http_error_default

🔴   File "urllib\request.py", line 643, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 Note this traceback was caught by reporter and has been added to the log (HTTP Error 502: Bad Gateway)
🟠 Unable to retrieve latest announcement
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 643, in http_error_default

🔴   File "urllib\request.py", line 643, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 
During handling of the above exception, another exception occurred:


🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 557, in error

🔴   File "urllib\request.py", line 557, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 749, in http_error_302

🔴   File "urllib\request.py", line 749, in http_error_302

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 643, in http_error_default

🔴   File "urllib\request.py", line 643, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 Note this traceback was caught by reporter and has been added to the log (HTTP Error 502: Bad Gateway)
🟠 Unable to retrieve latest announcement
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 643, in http_error_default

🔴   File "urllib\request.py", line 643, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 
During handling of the above exception, another exception occurred:


🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 557, in error

🔴   File "urllib\request.py", line 557, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 749, in http_error_302

🔴   File "urllib\request.py", line 749, in http_error_302

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 643, in http_error_default

🔴   File "urllib\request.py", line 643, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 Note this traceback was caught by reporter and has been added to the log (HTTP Error 502: Bad Gateway)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 208, in setSettings

🔴   File ".\tools.py", line 208, in setSettings

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 291, in restartClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 270, in closeClocks

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1407, in close

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 RuntimeError: Internal C++ object (Clock) already deleted.

🔴 Note this traceback was caught by reporter and has been added to the log (Internal C++ object (Clock) already deleted.)
🟠 Unable to retrieve latest announcement
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 643, in http_error_default

🔴   File "urllib\request.py", line 643, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 
During handling of the above exception, another exception occurred:


🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File ".\settings.py", line 3250, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 557, in error

🔴   File "urllib\request.py", line 557, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 749, in http_error_302

🔴   File "urllib\request.py", line 749, in http_error_302

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 643, in http_error_default

🔴   File "urllib\request.py", line 643, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 urllib.error.HTTPError: HTTP Error 502: Bad Gateway

🔴 Note this traceback was caught by reporter and has been added to the log (HTTP Error 502: Bad Gateway)
🔵 Copying log to the clipboard...
```

**Comment by RandyJae** [comment]
Windows 11
