### ISSUE TITLE
Syncing time (internet enable or not) constantly stalls

### ISSUE THREAD

**Issue by ianl50** [marticliment/ElevenClock#1248]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

Time syncing stalls constantly and as far as I can tell, randomly, whether Internet Sync is enabled or not.

ElevenClock version 4.2.2

Win11 22621.2215

### ElevenClock Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.0 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 4.2.2 (v4.22) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 145,145,145,100.0
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1345, 818, 200, 46)
🔵 Full screen rect:  (0, 0, 1536, 864)
🟡 Using custom font color: 0,0,0
🔵 Font families   : []
🔵 Custom font     : Arial Black,10,-1,5,900,0,0,0,0,0,0,0,0,0,0,1,Regular
🔵 Font size: 10.0
🟢 Loaded date time format: %#I:%M %p
%A
%#d/%m/%Y
🔵 Loaded date time format: <p style="line-height:0.7"><span>%#I:%M %p<br>%A<br>%#d/%m/%Y</span></p>  (clock 0
🟢 Loaded clocks in 0.7198834419250488
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Language file up-to-date
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 145,145,145,100.0
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1345, 818, 200, 46)
🔵 Full screen rect:  (0, 0, 1536, 864)
🟡 Using custom font color: 0,0,0
🔵 Font families   : []
🔵 Custom font     : Arial Black,10,-1,5,900,0,0,0,0,0,0,0,0,0,0,1,Regular
🔵 Font size: 10.0
🟢 Loaded date time format: %#I:%M %p
%A
%#d/%m/%Y
🔵 Loaded date time format: <p style="line-height:0.7"><span>%#I:%M %p<br>%A<br>%#d/%m/%Y</span></p>  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🟢 Loaded everything in 3.483976364135742
🔵 Restart loop: 1
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 145,145,145,100.0
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1345, 818, 200, 46)
🔵 Full screen rect:  (0, 0, 1536, 864)
🟡 Using custom font color: 0,0,0
🔵 Font families   : []
🔵 Custom font     : Arial Black,10,-1,5,900,0,0,0,0,0,0,0,0,0,0,1,Regular
🔵 Font size: 10.0
🟢 Loaded date time format: %#I:%M %p
%A
%#d/%m/%Y
🔵 Loaded date time format: <p style="line-height:0.7"><span>%#I:%M %p<br>%A<br>%#d/%m/%Y</span></p>  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: dddd, d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, d MMMM yyyy
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 145,145,145,100.0
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1345, 818, 200, 46)
🔵 Full screen rect:  (0, 0, 1536, 864)
🔵 Restart loop: 1
🟡 Using custom font color: 0,0,0
🔵 Font families   : []
🔵 Custom font     : Arial Black,10,-1,5,900,0,0,0,0,0,0,0,0,0,0,1,Regular
🔵 Font size: 10.0
🟢 Loaded date time format: %#I:%M %p
%A
%#d/%m/%Y
🔵 Loaded date time format: <p style="line-height:0.7"><span>%#I:%M %p<br>%A<br>%#d/%m/%Y</span></p>  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: dddd, d MMMM yyyy
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 221, in getSettingsValue

🔴   File ".\tools.py", line 221, in getSettingsValue

🔴 KeyError: 'langValue'

🔴 KeyError: 'langValue'

🔴 
During handling of the above exception, another exception occurred:


🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 223, in getSettingsValue

🔴   File ".\tools.py", line 223, in getSettingsValue

🔴 PermissionError: [Errno 13] Permission denied: 'C:\\Users\\lmn\\.elevenclock\\lang'

🔴 PermissionError: [Errno 13] Permission denied: 'C:\\Users\\lmn\\.elevenclock\\lang'

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 13] Permission denied: 'C:\\Users\\lmn\\.elevenclock\\lang')
🔵 Showing tooltip
🔵 Long date string: dddd, d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, d MMMM yyyy
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔵 Saving log...
🟢 log saved successfully
🔵 Showing tooltip
🔵 Long date string: dddd, d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, d MMMM yyyy
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔵 Showing tooltip
🔵 Long date string: dddd, d MMMM yyyy
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔵 Copying log to the clipboard...
```

**Comment by marticliment** [comment]
Hello,

could you please provide more details or a video of the issue?

Thanks!
