### ISSUE TITLE
[BUG] (Enter your description here)Eleven clock shuts when opening file explorer

### ISSUE THREAD

**Issue by 85rx7se** [marticliment/ElevenClock#1268]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

Windows 11 Pro and Elevenclock 4.3.0 Sometimes when opening Windows File Explorer Elevenclock 
disappears from the taskbar. It will return if I do a Restart of the computer ... Please see if this can 
be corrected ... Very annoying but otherwise a great program ... Thank you  

### Steps to reproduce the issue

Opening Windows File Explorer

### ElevenClock Log

```text
Do not have at this time
```

### Relevant information

WIndows 11 Pro 

### Screenshots and videos

NA

**Comment by marticliment** [comment]
Hello,

Which Windows build number are you running?

**Comment by marticliment** [comment]
Can you please send a video of the issue?

Also, please check if EleveClock still runs on the taskbar after opening explorer

**Comment by 85rx7se** [comment]
Marti,
This does not happen all the time. When it does happenmy taskbar is back to the built in normal windows clock.The only way to get elevenclock back is a restart of thecomputer. Next time it happens I will grab a screenshot
How do I check if Elevenclock still runs on the taskbarafter it disappears ? 

Bruce 




    On Thursday, October 5, 2023 at 10:30:19 AM EDT, Martí Climent ***@***.***> wrote:  
 
 


Can you please send a video of the issue?

Also, please check if EleveClock still runs on the taskbar after opening explorer

**Comment by 85rx7se** [comment]
I can get it back by going to my program list onthe start menu and clicking on elevenclock again.

Screenshot of how it is when it is working



    On Thursday, October 5, 2023 at 10:30:19 AM EDT, Martí Climent ***@***.***> wrote:  
 
 


Can you please send a video of the issue?

Also, please check if EleveClock still runs on the taskbar after opening explorer

**Comment by 85rx7se** [comment]
I do not have an Icon for elevenclock on the taskbarand the process is still listed in taskmanagerFortunately, I can restore it by clicking the programin the Start Menu program list 

    On Thursday, October 5, 2023 at 12:03:49 PM EDT, Martí Climent ***@***.***> wrote:  
 
 


Hello @85rx7se,

I cannot see images attached by mail.

ElevenClock has an icon on the taskbar, appart from the clock, so if this icon disappears when the clock is hidden it means ElevenClock process died. You can also check if ElevenClock is running by lokking on Task Manager

**Comment by marticliment** [comment]
Can you please share the logs of a running instance of ElevenClock?

Thanks!

**Comment by 85rx7se** [comment]
Where are the log files for this application ?

    On Thursday, October 5, 2023 at 12:12:13 PM EDT, Martí Climent ***@***.***> wrote:  
 
 


Can you please share the logs of a running instance of ElevenClock?

Thanks!

**Comment by marticliment** [comment]
ElevenClock Settings -> Scroll down -> Debugging information -> Open log

**Comment by 85rx7se** [comment]
Here is the log file ... we will see if the issue 
persists or not


    On Thursday, October 5, 2023 at 12:36:59 PM EDT, Martí Climent ***@***.***> wrote:  
 
 


ElevenClock Settings -> Scroll down -> Debugging information -> Open log

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
  
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.0 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 4.3.0 (v4.3) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 0,255,0,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1336, 825, 200, 39)
🔵 Full screen rect:  (0, 0, 1536, 864)
🟡 Using custom font color: 0,0,0
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %I:%M:%S  %p\n%m/%d/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🟢 Loaded clocks in 0.22799301147460938
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1431, in loadInternetTimeOffset

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1431, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 503, in open

🔴   File "urllib\request.py", line 503, in open

🔴   File "urllib\request.py", line 322, in __init__

🔴   File "urllib\request.py", line 322, in __init__

🔴   File "urllib\request.py", line 348, in full_url

🔴   File "urllib\request.py", line 348, in full_url

🔴   File "urllib\request.py", line 377, in _parse

🔴   File "urllib\request.py", line 377, in _parse

🔴 ValueError: unknown url type: 'time-a.nist.gov'

🔴 ValueError: unknown url type: 'time-a.nist.gov'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: 'time-a.nist.gov')
🔵 Restart loop: 1
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 130, in __init__

🔴   File ".\settings.py", line 130, in __init__

🔴 UnboundLocalError: cannot access local variable 'langName' where it is not associated with a value

🔴 UnboundLocalError: cannot access local variable 'langName' where it is not associated with a value

🔴 Note this traceback was caught by reporter and has been added to the log (cannot access local variable 'langName' where it is not associated with a value)
🔵 Language file up-to-date
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 1.2550978660583496
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 0,255,0,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1336, 825, 200, 39)
🔵 Full screen rect:  (0, 0, 1536, 864)
🟡 Using custom font color: 0,0,0
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %I:%M:%S  %p\n%m/%d/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1431, in loadInternetTimeOffset

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1431, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 503, in open

🔴   File "urllib\request.py", line 503, in open

🔴   File "urllib\request.py", line 322, in __init__

🔴   File "urllib\request.py", line 322, in __init__

🔴   File "urllib\request.py", line 348, in full_url

🔴   File "urllib\request.py", line 348, in full_url

🔴   File "urllib\request.py", line 377, in _parse

🔴   File "urllib\request.py", line 377, in _parse

🔴 ValueError: unknown url type: 'time-a.nist.gov'

🔴 ValueError: unknown url type: 'time-a.nist.gov'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: 'time-a.nist.gov')
🔵 Restart loop: 1
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: dddd, MMMM d, yyyy
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1431, in loadInternetTimeOffset

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1431, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 503, in open

🔴   File "urllib\request.py", line 503, in open

🔴   File "urllib\request.py", line 322, in __init__

🔴   File "urllib\request.py", line 322, in __init__

🔴   File "urllib\request.py", line 348, in full_url

🔴   File "urllib\request.py", line 348, in full_url

🔴   File "urllib\request.py", line 377, in _parse

🔴   File "urllib\request.py", line 377, in _parse

🔴 ValueError: unknown url type: 'time-a.nist.gov'

🔴 ValueError: unknown url type: 'time-a.nist.gov'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: 'time-a.nist.gov')
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🟡 loadTimeFormat function has not been defined yet!
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 0,255,0,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1336, 825, 200, 39)
🔵 Full screen rect:  (0, 0, 1536, 864)
🟡 Using custom font color: 0,0,0
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %I:%M:%S  %p\n%m/%d/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1431, in loadInternetTimeOffset

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1431, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 503, in open

🔴   File "urllib\request.py", line 503, in open

🔴   File "urllib\request.py", line 322, in __init__

🔴   File "urllib\request.py", line 322, in __init__

🔴   File "urllib\request.py", line 348, in full_url

🔴   File "urllib\request.py", line 348, in full_url

🔴   File "urllib\request.py", line 377, in _parse

🔴   File "urllib\request.py", line 377, in _parse

🔴 ValueError: unknown url type: 'time-a-.nist.gov'

🔴 ValueError: unknown url type: 'time-a-.nist.gov'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: 'time-a-.nist.gov')
🔵 Restart loop: 1
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1431, in loadInternetTimeOffset

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1431, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 503, in open

🔴   File "urllib\request.py", line 503, in open

🔴   File "urllib\request.py", line 322, in __init__

🔴   File "urllib\request.py", line 322, in __init__

🔴   File "urllib\request.py", line 348, in full_url

🔴   File "urllib\request.py", line 348, in full_url

🔴   File "urllib\request.py", line 377, in _parse

🔴   File "urllib\request.py", line 377, in _parse

🔴 ValueError: unknown url type: 'time-a-.nist.gov'

🔴 ValueError: unknown url type: 'time-a-.nist.gov'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: 'time-a-.nist.gov')
🟡 loadTimeFormat function has not been defined yet!
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 0,255,0,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1336, 825, 200, 39)
🔵 Full screen rect:  (0, 0, 1536, 864)
🟡 Using custom font color: 0,0,0
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %I:%M:%S  %p\n%m/%d/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1431, in loadInternetTimeOffset

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1431, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 503, in open

🔴   File "urllib\request.py", line 503, in open

🔴   File "urllib\request.py", line 322, in __init__

🔴   File "urllib\request.py", line 322, in __init__

🔴   File "urllib\request.py", line 348, in full_url

🔴   File "urllib\request.py", line 348, in full_url

🔴   File "urllib\request.py", line 377, in _parse

🔴   File "urllib\request.py", line 377, in _parse

🔴 ValueError: unknown url type: 'time-a-g.nist.gov'

🔴 ValueError: unknown url type: 'time-a-g.nist.gov'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: 'time-a-g.nist.gov')
🔵 Restart loop: 1
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1431, in loadInternetTimeOffset

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1431, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 503, in open

🔴   File "urllib\request.py", line 503, in open

🔴   File "urllib\request.py", line 322, in __init__

🔴   File "urllib\request.py", line 322, in __init__

🔴   File "urllib\request.py", line 348, in full_url

🔴   File "urllib\request.py", line 348, in full_url

🔴   File "urllib\request.py", line 377, in _parse

🔴   File "urllib\request.py", line 377, in _parse

🔴 ValueError: unknown url type: 'time-a-g.nist.gov'

🔴 ValueError: unknown url type: 'time-a-g.nist.gov'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: 'time-a-g.nist.gov')
🔵 Showing tooltip
🔵 Long date string: dddd, MMMM d, yyyy
Action: ('win', 'n')
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔵 Saving log...

**Comment by yrjarv** [comment]
Not sure if this is related, but ElevenClock disappears whenever I restart explorer.exe from the task manager. Maybe the underlying reason for these two issues is the same?

**Comment by marticliment** [comment]
This is expected, you will need to restart ElevenClock. This happens since ElevenClock calculates some coordinates based on the taskbar's position, size and attributes, and if explorer.exe is killed and restarted, the taskbar handle changes, and ElevenClock therefore understands that the taskbar has been hidden

**Comment by TheRobstercraw** [comment]
Using Windows 11 keeps showing on the screen. See pic.

![Image](https://github.com/user-attachments/assets/4c3dc39d-cbc1-416b-a604-69f8893e4f00)
