### ISSUE TITLE
[BUG] (Enter your description here)

### ISSUE THREAD

**Issue by bhami3** [marticliment/ElevenClock#1271]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

ElevenClock 4.3.0 shows a time which is one hour ahead of the correct time. The displayed time is correct as soon as I exit ElevenClock.

### Steps to reproduce the issue

Run ElevenClock at boot.

### ElevenClock Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.0009996891021728516 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 4.3.0 (v4.3) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(2360, 1394, 200, 46)
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M\n%Y-%m-%d  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🟢 Loaded clocks in 0.3935549259185791
🔵 Restart loop: 1
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 130, in __init__

🔴   File ".\settings.py", line 130, in __init__

🔴 UnboundLocalError: cannot access local variable 'langName' where it is not associated with a value

🔴 UnboundLocalError: cannot access local variable 'langName' where it is not associated with a value

🔴 Note this traceback was caught by reporter and has been added to the log (cannot access local variable 'langName' where it is not associated with a value)
🔵 Language file up-to-date
🔵 (worldtimeapi.org) Time offset set to -3600.28280711174
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(2360, 1394, 200, 46)
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M\n%Y-%m-%d  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🟢 Loaded everything in 2.248277425765991
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(2360, 1394, 200, 46)
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M\n%Y-%m-%d  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 (worldtimeapi.org) Time offset set to -3600.2665078639984
🔵 Restart loop: 2
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Restart loop: 1
🔵 (worldtimeapi.org) Time offset set to -3600.2844610214233
🔵 Showing tooltip
🔵 Long date string: dddd, d MMMM, yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, d MMMM, yyyy
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔵 Starting update check
🔵 Version URL: https://versions.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Copying log to the clipboard...
```

**Comment by marticliment** [comment]
Please disable internet time from ElevenClock settings
