### ISSUE TITLE
[BUG] (Alternative Clock Position doesn't show seconds)

### ISSUE THREAD

**Issue by SpinchGang** [marticliment/ElevenClock#1297]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

For me, the Alternative Clock Position would be a useful feature to use, however it doesn't show seconds when enabled

### Steps to reproduce the issue

Enable Alternative Clock Position

### ElevenClock Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.012119531631469727 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.9.3 (v3.93) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide6.QtCore.QRect(2360, 1394, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#m/%#d/%Y
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Full screen rect:  (0, 0, 2560, 1440)
can't parse ""
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🟢 Loaded clocks in 0.602031946182251
🔵 Language file up-to-date
🔵 Restart loop: 1
🟣 Expected AttributeError on checkAndUpdateBackground
{'System language': 'default', 'Arabic - عربي\u200e (62%)': 'ar', 'Bosnian - Bosanski (6%)': 'bs', 'Bulgarian - български (18%)': 'bg', 'Catalan - Català': 'ca', 'Czech - Čeština (99%)': 'cs', 'Danish - Dansk (98%)': 'da', 'German - Deutsch (99%)': 'de', 'Greek - Ελληνικά (18%)': 'el', 'English - English': 'en', 'Spanish - Español (99%)': 'es', 'Estonian - eesti (92%)': 'et', 'Persian - فارسی\u200e (5%)': 'fa', 'Finnish - Suomi (63%)': 'fi', 'French - Français (99%)': 'fr', 'Hebrew - עִבְרִית\u200e (92%)': 'he', 'Croatian - Hrvatski (11%)': 'hr', 'Hungarian - Magyar (91%)': 'hu', 'Indonesian - Bahasa Indonesia (92%)': 'id', 'Italian - Italiano (65%)': 'it', 'Japanese - 日本語 (93%)': 'ja', 'Korean - 한국어 (99%)': 'ko', 'Lithuanian - Lietuvių (22%)': 'lt', 'Latvian - Latviski (61%)': 'lv', 'Norwegian (bokmål) (92%)': 'nb', 'Dutch - Nederlands (80%)': 'nl', 'Norwegian (nynorsk) (67%)': 'nn', 'Polish - Polski (96%)': 'pl', 'Portuguese (Brazil) (99%)': 'pt_BR', 'Portuguese (Portugal) (99%)': 'pt_PT', 'Romanian - Română (92%)': 'ro', 'Russian - Русский (92%)': 'ru', 'Sinhala - සිංහල': 'si', 'Slovak - Slovenčina (30%)': 'sk', 'Serbian - Srpski (22%)': 'sr', 'Swedish - Svenska (78%)': 'sv', 'Thai - ภาษาไทย (82%)': 'th', 'Turkish - Türkçe (99%)': 'tr', 'Ukranian - Yкраї́нська (93%)': 'ua', 'Vietnamese - Tiếng Việt (38%)': 'vi', 'Simplified Chinese (China) (99%)': 'zh_CN', 'Traditional Chinese (Taiwan) (99%)': 'zh_TW'}
🟣 Expected AttributeError on checkAndUpdateBackground
🟣 Expected AttributeError on checkAndUpdateBackground
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 1.542370319366455
🔵 Version URL: http://ww25.versions.somepythonthings.tk/versions/elevenclock.ver?subid1=20231211-1220-0222-bcae-232de917386a
🔵 Showing tooltip
🔵 Short date string: h:mm tt
🔵 TZ 1 is None
🔵 Long date string: dddd, MMMM d, yyyy
Action: ('win', 'n')
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 139, in updateIfPossible

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🔵 Showing tooltip
🔵 Short date string: h:mm tt
🔵 TZ 1 is None
🔵 Long date string: dddd, MMMM d, yyyy
🔵 Announcement URL: http://ww25.somepythonthings.tk/resources/elevenclock.announcement?subid1=20231211-1220-1369-9dd4-ef7628338cc4
🟠 Unable to retrieve latest announcement
🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3021, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 557, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 749, in http_error_302

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 643, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 436: 

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3030, in loadAnnouncements

🔴 IndexError: list index out of range

🔴 Note this traceback was caught by reporter and has been added to the log (list index out of range)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#m/%#d/%Y
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide6.QtCore.QRect(960, 456, 640, 480)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#m/%#d/%Y
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#m/%#d/%Y
🔵 Restart loop: 1
🟢 Cached text input host hwnd: 66524
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#m/%#d/%Y
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide6.QtCore.QRect(2360, 1394, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#m/%#d/%Y
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#m/%#d/%Y
🔵 Restart loop: 1
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#m/%#d/%Y
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide6.QtCore.QRect(960, 456, 640, 480)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#m/%#d/%Y
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#m/%#d/%Y
🔵 Restart loop: 1
🔵 Copying log to the clipboard...
```

### Screenshots and videos

![ElevenClock Bug Report 1](https://github.com/marticliment/ElevenClock/assets/119467985/617d5b44-b431-4771-a254-b5f75e0184c6)
![ElevenClock Bug Report 2](https://github.com/marticliment/ElevenClock/assets/119467985/3b381bf2-c5e0-4aa3-88d8-4f3a9eb4666e)

**Comment by marticliment** [comment]
Hello,


You are using an outdated version of ElevenClock.

Please install ElevenClock from the Microsoft Store to perform an upgrade
