### ISSUE TITLE
ElevenClock is not persistent in my Windows 11 taskbar

### ISSUE THREAD

**Issue by phoenix5395** [marticliment/ElevenClock#1328]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

After configuring ElevenClock for my taskbar, the application disappears when the ElevenClock Settings dialog is closed. I have attached some simple screenshots. Also, after waking or restarting the computer, my custom ElevenClock clock does not appear in the taskbar unless I proactively launch ElevenClock (or any other app for that matter.)

### Steps to reproduce the issue

I have restarted the computer several times and ensured that ElevenClock is in the Windows Startup folder. Simply put, any time a Windows app is not active on screen, neither is ElevenClock in my taskbar.

### ElevenClock Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.0030205249786376953 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 4.3.2 (v4.32) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(2320, 1394, 200, 46)
🔵 Full screen rect:  (0, 0, 2560, 1440)
🟢 Custom valid shortcut specified (for double click): ['toggle_setting_dblclick']
🟡 Using custom font color: 0,255,0
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,50,0,0,0,0,0,Regular
🔵 Font size: 9.0
🔵 Loaded date time format: %#I:%M:%S  %p\n%#m/%#d/%Y  (clock 0
🟢 Loaded clocks in 0.9763741493225098
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Language file up-to-date
🟡 loadTimeFormat function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 2.9246232509613037
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(2320, 1394, 200, 46)
🔵 Full screen rect:  (0, 0, 2560, 1440)
🟢 Custom valid shortcut specified (for double click): ['toggle_setting_dblclick']
🟡 Using custom font color: 0,255,0
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,50,0,0,0,0,0,Regular
🔵 Font size: 9.0
🔵 Loaded date time format: %#I:%M:%S  %p\n%#m/%#d/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 11001] getaddrinfo failed)
🔵 Starting update check
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(2320, 1394, 200, 46)
🔵 Full screen rect:  (0, 0, 2560, 1440)
🟢 Custom valid shortcut specified (for double click): ['toggle_setting_dblclick']
🟡 Using custom font color: 0,255,0
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,50,0,0,0,0,0,Regular
🔵 Font size: 9.0
🔵 Loaded date time format: %#I:%M:%S  %p\n%#m/%#d/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://www.marticliment.com/resources/christmas.png
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 11001] getaddrinfo failed)
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(2320, 1394, 200, 46)
🔵 Full screen rect:  (0, 0, 2560, 1440)
🟢 Custom valid shortcut specified (for double click): ['toggle_setting_dblclick']
🟡 Using custom font color: 0,255,0
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,50,0,0,0,0,0,Regular
🔵 Font size: 9.0
🔵 Loaded date time format: %#I:%M:%S  %p\n%#m/%#d/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(2320, 1394, 200, 46)
🔵 Full screen rect:  (0, 0, 2560, 1440)
🟢 Custom valid shortcut specified (for double click): ['toggle_setting_dblclick']
🟡 Using custom font color: 0,255,0
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,50,0,0,0,0,0,Regular
🔵 Font size: 9.0
🔵 Loaded date time format: %#I:%M:%S  %p\n%#m/%#d/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(2320, 1394, 200, 46)
🔵 Full screen rect:  (0, 0, 2560, 1440)
🟢 Custom valid shortcut specified (for double click): ['toggle_setting_dblclick']
🟡 Using custom font color: 0,255,0
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,50,0,0,0,0,0,Regular
🔵 Font size: 9.0
🔵 Loaded date time format: %#I:%M:%S  %p\n%#m/%#d/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(2320, 1394, 200, 46)
🔵 Full screen rect:  (0, 0, 2560, 1440)
🟢 Custom valid shortcut specified (for double click): ['toggle_setting_dblclick']
🟡 Using custom font color: 0,255,0
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,50,0,0,0,0,0,Regular
🔵 Font size: 9.0
🔵 Loaded date time format: %#I:%M:%S  %p\n%#m/%#d/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://www.marticliment.com/resources/christmas.png
🔵 Copying log to the clipboard...
```

### Screenshots and videos

![Screenshot 2024-03-17 155119](https://github.com/marticliment/ElevenClock/assets/163777576/f2274a47-d953-41b5-8a98-e350c9eb1fd9)

**Comment by marticliment** [comment]
> I have restarted the computer several times and ensured that ElevenClock is in the Windows Startup folder. Simply put, any time a Windows app is not active on screen, neither is ElevenClock in my taskbar.

Does clicking on the desktop make ElevenClock show up? Because when the taskbar has focus ElevenClock can't show over it.


Btw, please try to update ElevenClock to version 4.3.3 installing this version: https://github.com/marticliment/ElevenClock/releases/download/4.3.3/ElevenClock.Installer.exe

**Comment by phoenix5395** [comment]
Hi Marti,

Thank you for the prompt response. I managed to correct the disappearance
issue by toggling "Hide Windows 11 Taskbar" on and then back off again.
Please note that ElevenClock still shows when the Windows taskbar is hidden
(just an observation since my taskbar is always displayed.)

I will try installing version 4.3.3 later this evening...

Regards,
Curtis
