### ISSUE TITLE
[BUG] Unable to customize clock while using "Disable hiding the default windows clock"

### ISSUE THREAD

**Issue by Martok88** [marticliment/ElevenClock#1329]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

Hi. I'm using ElevenClock to move the clock to the left side of my taskbar, center align its text, and adjust its font size. I had an issue with an additional clock with no text appearing on logging in or exiting any full screen window, covering the system icons on the right side of the taskbar. After enabling the setting "Disable hiding the default windows clock" as suggested [here,](https://github.com/marticliment/ElevenClock/issues/1289) that particular issue was solved. 
However, on restarting ElevenClock, the clock font size has reverted, and that setting and others such as double click behavior no longer have any effect. The clock is still on the left, and the text is center aligned, but changing those settings doesn't do anything now.

### ElevenClock Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.0010008811950683594 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 4.3.2 (v4.32) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟡 Clock on the left
🔵 Clock geometry: PySide6.QtCore.QRect(0, 674, 200, 46)
🔵 Full screen rect:  (0, 0, 1280, 720)
🔵 Using automatic font color
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 12.0
🔵 Loaded date time format: %#I:%M %p\n%#m/%#d/%Y  (clock 0
🟢 Loaded clocks in 0.39340782165527344
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🔵 Restart loop: 1
🔵 Language file up-to-date
🔵 (worldtimeapi.org) Time offset set to -11.532048463821411
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to True
🟢 Loaded everything in 1.9919710159301758
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 11001] getaddrinfo failed)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 
During handling of the above exception, another exception occurred:


🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 163, in updateIfPossible

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 163, in updateIfPossible

🔴 AttributeError: 'Clock' object has no attribute 'progressbar'

🔴 AttributeError: 'Clock' object has no attribute 'progressbar'

🔴 Note this traceback was caught by reporter and has been added to the log ('Clock' object has no attribute 'progressbar')
🔵 Showing tooltip
🔵 Long date string: dddd, MMMM d, yyyy
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://www.marticliment.com/resources/christmas.png
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
```

**Comment by marticliment** [comment]
Hello,

I am afraid this might be caused by some corruption of the settings. Please try downloading ElevenClock 4.3.3 from [here](https://github.com/marticliment/ElevenClock/releases/download/4.3.3/ElevenClock.Installer.exe) and choosing "Reset ElevenClock" on the installer.

**Comment by Martok88** [comment]
Unfortunately I'm still experiencing the issue after a clean install.

**Comment by marticliment** [comment]
Could you please share a video of the issue?

**Comment by Martok88** [comment]
Using a custom font seems to have fixed this issue for me.
