### ISSUE TITLE
show second clock disabled, but still showing

### ISSUE THREAD

**Issue by LDWILLIAMS** [marticliment/ElevenClock#1340]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

 have elenclock in the left hand corner but a blank rectangle appears ib bottom right corner. I do Not currently have show second clock enabled, but have had that set previously. Is there any way to get around this please?

### Steps to reproduce the issue

I have no idea

### ElevenClock Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.007998943328857422 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 4.3.2 (v4.32) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 0,51,153,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟢 Clock on the bottom
🟡 Clock on the left
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(8, 1382, 200, 58)
🔵 Full screen rect:  (0, 0, 3440, 1440)
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 0,51,153,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟠 Clock is cover!!!
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock cover geometry: PySide6.QtCore.QRect(3248, 1382, 200, 58)
🔵 Full screen rect:  (0, 0, 3440, 1440)
🟡 Custom loaded date time format (clock 0): %a  %H:%M:%S\n%d/%m/:%y
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🟡 Using custom font color: 255,246,240
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 18.0
🟡 Custom loaded date time format (clock 0): %a  %H:%M:%S\n%d/%m/:%y
🔵 Initializing clock 1...
🟡 Not using taskbar background color
🔵 Using bg color: 0,51,153,100.0
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, DisableNotifications:True
🟢 Regular sized taskbar
🟡 Custom height being used!
🟢 Clock on the bottom
🟡 Clock on the left
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1065, 2102, 200, 58)
🔵 Full screen rect:  (1057, 1440, 2977, 2160)
🔵 Initializing clock 1...
🟡 Not using taskbar background color
🔵 Using bg color: 0,51,153,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟠 Clock is cover!!!
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock cover geometry: PySide6.QtCore.QRect(2785, 2102, 200, 58)
🔵 Full screen rect:  (1057, 1440, 2977, 2160)
🟡 Custom loaded date time format (clock 1): %a  %H:%M:%S\n%d/%m/:%y
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🟡 Using custom font color: 255,246,240
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 18.0
🟡 Custom loaded date time format (clock 1): %a  %H:%M:%S\n%d/%m/:%y
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, DisableNotifications:True
🔵 Initializing clock 2...
🟡 Not using taskbar background color
🔵 Using bg color: 0,51,153,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟢 Clock on the bottom
🟡 Clock on the left
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(-1912, 1022, 200, 58)
🔵 Full screen rect:  (-1920, 0, 0, 1080)
🔵 Initializing clock 2...
🟡 Not using taskbar background color
🔵 Using bg color: 0,51,153,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟠 Clock is cover!!!
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock cover geometry: PySide6.QtCore.QRect(-192, 1022, 200, 58)
🔵 Full screen rect:  (-1920, 0, 0, 1080)
🟡 Custom loaded date time format (clock 2): %a  %H:%M:%S\n%d/%m/:%y
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🟡 Using custom font color: 255,246,240
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 18.0
🔵 (worldtimeapi.org) Time offset set to -3.149160146713257
🔵 (worldtimeapi.org) Time offset set to -3.1489861011505127
🟡 Custom loaded date time format (clock 2): %a  %H:%M:%S\n%d/%m/:%y
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, DisableNotifications:True
🟢 Loaded clocks in 0.5265042781829834
🔵 (worldtimeapi.org) Time offset set to -3.045534133911133
🔵 (worldtimeapi.org) Time offset set to -3.0322201251983643
🔵 (worldtimeapi.org) Time offset set to -3.000476121902466
🔵 (worldtimeapi.org) Time offset set to -3.1279091835021973
🔵 Language file up-to-date
🔵 Restart loop: 1
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 1.228196382522583
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 11001] getaddrinfo failed)
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 0,51,153,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟢 Clock on the bottom
🟡 Clock on the left
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(8, 1382, 200, 58)
🔵 Full screen rect:  (0, 0, 3440, 1440)
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 0,51,153,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟠 Clock is cover!!!
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock cover geometry: PySide6.QtCore.QRect(3248, 1382, 200, 58)
🔵 Full screen rect:  (0, 0, 3440, 1440)
🟡 Custom loaded date time format (clock 0): %a  %H:%M:%S\n%d/%m/:%y
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🟡 Using custom font color: 255,246,240
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 18.0
🟡 Custom loaded date time format (clock 0): %a  %H:%M:%S\n%d/%m/:%y
🔵 Initializing clock 1...
🟡 Not using taskbar background color
🔵 Using bg color: 0,51,153,100.0
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, DisableNotifications:True
🟢 Regular sized taskbar
🟡 Custom height being used!
🟢 Clock on the bottom
🟡 Clock on the left
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1065, 2102, 200, 58)
🔵 Full screen rect:  (1057, 1440, 2977, 2160)
🔵 Initializing clock 1...
🟡 Not using taskbar background color
🔵 Using bg color: 0,51,153,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟠 Clock is cover!!!
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock cover geometry: PySide6.QtCore.QRect(2785, 2102, 200, 58)
🔵 Full screen rect:  (1057, 1440, 2977, 2160)
🟡 Custom loaded date time format (clock 1): %a  %H:%M:%S\n%d/%m/:%y
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🟡 Using custom font color: 255,246,240
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 18.0
🟡 Custom loaded date time format (clock 1): %a  %H:%M:%S\n%d/%m/:%y
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, DisableNotifications:True
🔵 Initializing clock 2...
🟡 Not using taskbar background color
🔵 Using bg color: 0,51,153,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟢 Clock on the bottom
🟡 Clock on the left
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(-1912, 1022, 200, 58)
🔵 Full screen rect:  (-1920, 0, 0, 1080)
🔵 Initializing clock 2...
🟡 Not using taskbar background color
🔵 Using bg color: 0,51,153,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟠 Clock is cover!!!
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock cover geometry: PySide6.QtCore.QRect(-192, 1022, 200, 58)
🔵 Full screen rect:  (-1920, 0, 0, 1080)
🔵 (worldtimeapi.org) Time offset set to -3.1498191356658936
🟡 Custom loaded date time format (clock 2): %a  %H:%M:%S\n%d/%m/:%y
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 (worldtimeapi.org) Time offset set to -3.14806866645813
🟡 Using custom font color: 255,246,240
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 18.0
🟡 Custom loaded date time format (clock 2): %a  %H:%M:%S\n%d/%m/:%y
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, DisableNotifications:True
🔵 (worldtimeapi.org) Time offset set to -3.1467933654785156
🔵 (worldtimeapi.org) Time offset set to -3.1490492820739746
🔵 (worldtimeapi.org) Time offset set to -3.1418488025665283
🔵 (worldtimeapi.org) Time offset set to -3.13749098777771
🔵 Restart loop: 1
🔵 (worldtimeapi.org) Time offset set to -3.1497559547424316
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 11001] getaddrinfo failed)
🔵 Showing tooltip
🔵 Long date string: dd MMMM yyyy
🔵 (worldtimeapi.org) Time offset set to -3.270176887512207
🔵 (worldtimeapi.org) Time offset set to -3.2701058387756348
🔵 (worldtimeapi.org) Time offset set to -3.270256757736206
🔵 (worldtimeapi.org) Time offset set to -3.268737554550171
🔵 (worldtimeapi.org) Time offset set to -3.2686309814453125
🔵 (worldtimeapi.org) Time offset set to -3.2785630226135254
🔵 Showing tooltip
🔵 Long date string: dd MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dd MMMM yyyy
Action: ('win', 'n')
Action: ('win', 'n')
Action: ('win', 'n')
Action: ('win', 'n')
🔵 Showing tooltip
🔵 Long date string: dd MMMM yyyy
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔵 Showing tooltip
🔵 Long date string: dd MMMM yyyy
🔵 Saving log...
```

**Comment by marticliment** [comment]
Go to Experimental features -> Select "Disable hiding the default windows clock"

**Comment by LDWILLIAMS** [comment]
Just found that, thanks!
(lil tip, do Please say which section a setting is under, thank you! :) )

Any way of hiding the clock on a secondd monitor?

**Comment by LDWILLIAMS** [comment]
I'll give that a try - thanks!

**Comment by LDWILLIAMS** [comment]
nope - cant open Any of the settings when I try that route :(

**Comment by LDWILLIAMS** [comment]
How do you set transparent?

**Comment by marticliment** [comment]
You should be able to specify the alpha channel on the color selector
