### ISSUE TITLE
[BUG] Text cut off in Settings > Date & Time Settings > Custom format rules

### ISSUE THREAD

**Issue by mcsilver** [marticliment/ElevenClock#1344]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose))

### Describe your issue

In ElevenClock Settings, the bullet point text for _Date & Time Settings_, _Custom format rules_, the bullet points are cut off, so I can't read them all. I tried copying them to the clipboard, but they don't highlight, scrolling within the text, searching for the same text online, and restarting the computer.

### Steps to reproduce the issue

Just open the app's settings and go to Date & Time Settings > Custom format rules

### ElevenClock Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.0010020732879638672 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 4.3.3 (v4.33) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 255,255,255,100
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(3651, 2114, 200, 46)
🔵 Full screen rect:  (0, 0, 3840, 2160)
🟡 Using custom font color: 0,0,0
🔵 Font families   : []
🔵 Custom font     : Arial,10.5,-1,5,700,0,0,0,0,0,0,0,0,0,0,1,Narrow Bold
🔵 Font size: 10.0
🟡 Desktop button enabled
🟡 Custom loaded date time format (clock 0): %H:%M:%S %p\n%a %b %d, %Y
🟢 Loaded clocks in 0.23832178115844727
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🔵 Language file up-to-date
🔵 Restart loop: 1
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to True
🟢 Loaded everything in 1.2348268032073975
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 255,255,255,100
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(3651, 2114, 200, 46)
🔵 Full screen rect:  (0, 0, 3840, 2160)
🟡 Using custom font color: 0,0,0
🔵 Font families   : []
🔵 Custom font     : Arial,10.5,-1,5,700,0,0,0,0,0,0,0,0,0,0,1,Narrow Bold
🔵 Font size: 10.0
🟡 Desktop button enabled
🟡 Custom loaded date time format (clock 0): %H:%M:%S %p\n%a %b %d, %Y
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🔵 Restart loop: 1
🔵 Version URL: https://www.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴 ValueError: Invalid format string

🔴 ValueError: Invalid format string

🔴 Note this traceback was caught by reporter and has been added to the log (Invalid format string)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴 ValueError: Invalid format string

🔴 ValueError: Invalid format string

🔴 Note this traceback was caught by reporter and has been added to the log (Invalid format string)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴 ValueError: Invalid format string

🔴 ValueError: Invalid format string

🔴 Note this traceback was caught by reporter and has been added to the log (Invalid format string)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴 ValueError: Invalid format string

🔴 ValueError: Invalid format string

🔴 Note this traceback was caught by reporter and has been added to the log (Invalid format string)
🟡 loadTimeFormat function has not been defined yet!
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 255,255,255,100
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(3651, 2114, 200, 46)
🔵 Full screen rect:  (0, 0, 3840, 2160)
🟡 Using custom font color: 0,0,0
🔵 Font families   : []
🔵 Custom font     : Arial,10.5,-1,5,700,0,0,0,0,0,0,0,0,0,0,1,Narrow Bold
🔵 Font size: 10.0
🟡 Desktop button enabled
🟡 Custom loaded date time format (clock 0): %I:%M:%S %p\n%a %b %d, %Y
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🔵 Restart loop: 1
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴 ValueError: Invalid format string

🔴 ValueError: Invalid format string

🔴 Note this traceback was caught by reporter and has been added to the log (Invalid format string)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴 ValueError: Invalid format string

🔴 ValueError: Invalid format string

🔴 Note this traceback was caught by reporter and has been added to the log (Invalid format string)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴 ValueError: Invalid format string

🔴 ValueError: Invalid format string

🔴 Note this traceback was caught by reporter and has been added to the log (Invalid format string)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴 ValueError: Invalid format string

🔴 ValueError: Invalid format string

🔴 Note this traceback was caught by reporter and has been added to the log (Invalid format string)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴 ValueError: Invalid format string

🔴 ValueError: Invalid format string

🔴 Note this traceback was caught by reporter and has been added to the log (Invalid format string)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴 ValueError: Invalid format string

🔴 ValueError: Invalid format string

🔴 Note this traceback was caught by reporter and has been added to the log (Invalid format string)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\settings.py", line 3138, in updateText

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴   File ".\tools.py", line 174, in evaluate_expression_string

🔴 ValueError: Invalid format string

🔴 ValueError: Invalid format string

🔴 Note this traceback was caught by reporter and has been added to the log (Invalid format string)
🟡 loadTimeFormat function has not been defined yet!
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 255,255,255,100
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(3651, 2114, 200, 46)
🔵 Full screen rect:  (0, 0, 3840, 2160)
🟡 Using custom font color: 0,0,0
🔵 Font families   : []
🔵 Custom font     : Arial,10.5,-1,5,700,0,0,0,0,0,0,0,0,0,0,1,Narrow Bold
🔵 Font size: 10.0
🟡 Desktop button enabled
🟡 Custom loaded date time format (clock 0): %#I:%M:%S %p\n%a %b %d, %Y
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🔵 Restart loop: 1
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 255,255,255,100
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(3651, 2114, 200, 46)
🔵 Full screen rect:  (0, 0, 3840, 2160)
🟡 Using custom font color: 0,0,0
🔵 Font families   : []
🔵 Custom font     : Arial,10.5,-1,5,700,0,0,0,0,0,0,0,0,0,0,1,Narrow Bold
🔵 Font size: 10.0
🟡 Desktop button enabled
🟡 Custom loaded date time format (clock 0): %#I:%M:%S %p\n%a %b %d, %Y
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🔵 Restart loop: 1
🟡 NOT showing tooltip, it has been disabled
🔵 Copying log to the clipboard...
```

### Relevant information

Windows 11 Pro 10.0.22631 23H2 (22631.3737)
ElevenClock 4.3.3 64bit (version code 4.33)

My resolution is 3840x2160.
Windows text size is 100%.
 Windows scale is 100%.

![ElevenClock Settings Text is Cut Off, 2024-06-24](https://github.com/marticliment/ElevenClock/assets/2747224/2d170c5d-978d-4e36-9292-1b52d178a9d5)

**Comment by mcsilver** [comment]
Does the "completed" status mean that it will be in the next release or that it is already released? In Settings, I have _Automatically check for updates_ checked, but I don't have the fix yet.

No rush, just want to know what to expect. Thanks!

**Comment by marticliment** [comment]
On next release

**Comment by mcsilver** [comment]
Thanks.

[Description: ***@***.***
Craig Silver
Owner Operator
t. 604-339-7417 | e. ***@***.******@***.***>
computer services with a personal touch
