### ISSUE TITLE
I moved the clock to the upper right of my desktop but there is a blue rectangle with no information in it that remains at the bottom right of my taskbar (the default position, I think).

### ISSUE THREAD

**Issue by RogerThat-Dave** [marticliment/ElevenClock#1364]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose)).

### Describe your issue

I moved the clock to the upper right of my desktop but there is a blue rectangle with no information in it that remains at the bottom right of my taskbar (the default position, I think).

### Steps to reproduce the issue

I just used the Clock settings to change the location of the clock to the upper right corner.  Originally this was just the default location (bottom of the screen - right side of the task bar).  That's all I did.  The result is that the clock DOES show in the top right but there is a blue background the same size as the clock in the taskbar.  It only appears when the clock is dispaying.

### ElevenClock Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.006084442138671875 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 4.3.2 (v4.32) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 3,3,3,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟡 ElevenClock set to hide with the taskbar
🟡 Clock on the top
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1722, -1, 200, 62)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 3,3,3,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟠 Clock is cover!!!
🟡 ElevenClock set to hide with the taskbar
🟡 Clock on the top
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock cover geometry: PySide6.QtCore.QRect(1722, 1015, 200, 62)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Loaded date time format: %#I:%M %p\n%#m/%#d/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🟡 Using custom font color: 255,170,0
🔵 Font families   : []
🔵 Custom font     : Bahnschrift,14,-1,5,700,0,0,0,0,0,0,0,0,0,0,1,Bold
🔵 Font size: 14.0
🟡 Desktop button enabled
🔵 Loaded date time format: %#I:%M %p\n%#m/%#d/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:True, DisableNotifications:False
🟢 Loaded clocks in 0.6808385848999023
🔵 Restart loop: 1
🔵 Language file up-to-date
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to True
🟢 Loaded everything in 2.6599974632263184
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 11001] getaddrinfo failed)
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 3,3,3,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟡 ElevenClock set to hide with the taskbar
🟡 Clock on the top
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1722, -1, 200, 62)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 3,3,3,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟠 Clock is cover!!!
🟡 ElevenClock set to hide with the taskbar
🟡 Clock on the top
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock cover geometry: PySide6.QtCore.QRect(1722, 1015, 200, 62)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Loaded date time format: %#I:%M %p\n%#m/%#d/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🟡 Using custom font color: 255,170,0
🔵 Font families   : []
🔵 Custom font     : Bahnschrift,14,-1,5,700,0,0,0,0,0,0,0,0,0,0,1,Bold
🔵 Font size: 14.0
🟡 Desktop button enabled
🔵 Loaded date time format: %#I:%M %p\n%#m/%#d/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:True, DisableNotifications:False
🔵 Restart loop: 1
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 3,3,3,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟡 ElevenClock set to hide with the taskbar
🟡 Clock on the top
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1722, -1, 200, 62)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 3,3,3,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟠 Clock is cover!!!
🟡 ElevenClock set to hide with the taskbar
🟡 Clock on the top
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock cover geometry: PySide6.QtCore.QRect(1722, 1015, 200, 62)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Loaded date time format: %#I:%M %p\n%#m/%#d/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🟡 Using custom font color: 255,170,0
🔵 Font families   : []
🔵 Custom font     : Bahnschrift,14,-1,5,700,0,0,0,0,0,0,0,0,0,0,1,Bold
🔵 Font size: 14.0
🟡 Desktop button enabled
🔵 Loaded date time format: %#I:%M %p\n%#m/%#d/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:True, DisableNotifications:False
🔵 Restart loop: 1
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🟠 Can't disconnect signal!
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 3,3,3,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟡 ElevenClock set to hide with the taskbar
🟡 Clock on the top
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1722, -1, 200, 62)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 3,3,3,100.0
🟢 Regular sized taskbar
🟡 Custom height being used!
🟠 Clock is cover!!!
🟡 ElevenClock set to hide with the taskbar
🟡 Clock on the top
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock cover geometry: PySide6.QtCore.QRect(1722, 1015, 200, 62)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Restart loop: 1
🔵 Loaded date time format: %#I:%M %p\n%#m/%#d/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🟡 Using custom font color: 255,170,0
🔵 Font families   : []
🔵 Custom font     : Bahnschrift,14,-1,5,700,0,0,0,0,0,0,0,0,0,0,1,Bold
🔵 Font size: 14.0
🟡 Desktop button enabled
🔵 Loaded date time format: %#I:%M %p\n%#m/%#d/%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:True, DisableNotifications:False
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 11001] getaddrinfo failed)
🔵 Copying log to the clipboard...
```

**Comment by marticliment** [comment]
Please disable the following option:

ElevenClock Settings -> experimental settings -> Disable hiding default windows clock

**Comment by RogerThat-Dave** [comment]
Thank you, Marti. I appreciate you getting back to me on that.

Dave

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
