### ISSUE TITLE
[BUG] (Enter your description here)

### ISSUE THREAD

**Issue by MASC-Github** [marticliment/ElevenClock#1373]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose)).

### Describe your issue

Jedes mal wen ich ein beliebiges geöffnetes Fenster schliesse verschwindet auch die Uhr von Eleven Clock. Ich möchte aber, dass die Uhr von Eleven Clock immer im Vordergrund also auch auf dem Desktop angezeigt wird. Dies aber auch wenn die Uhr der Taskleiste ausgeschaltet ist. Ich habe folgendes aktiviert Pinne die Uhr an den Desktop.

### ElevenClock Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.0010008811950683594 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 4.4.1.1 (v4.411) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "de"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 0,0,255,100.0
🟡 Clock pinned to desktop
🟢 Clock on the bottom
🟢 Clock on the right
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(2360, 1346, 200, 46)
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 0,0,255,100.0
🟡 Clock pinned to desktop
🟢 Clock on the bottom
🟡 Clock on the left
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(0, 1346, 200, 46)
🔵 Full screen rect:  (0, 0, 2560, 1440)
🟢 Custom valid shortcut specified: ['win', 'n']
🟡 Using custom font color: 255,255,255
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,50,0,0,0,0,0,Regular
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M:%S \n%A\n%d.%m.%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🟢 Custom valid shortcut specified: ['win', 'n']
🟡 Using custom font color: 255,255,255
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,50,0,0,0,0,0,Regular
🔵 Font size: 9.0
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 373, in _parse

🔴   File "urllib\request.py", line 373, in _parse

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"')
🔵 Loaded date time format: %H:%M:%S \n%A\n%d.%m.%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🟢 Loaded clocks in 0.32585692405700684
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 373, in _parse

🔴   File "urllib\request.py", line 373, in _parse

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"')
🔵 Language file up-to-date
🔵 Restart loop: 1
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to True
🟢 Loaded everything in 0.9415106773376465
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 500, in destroy

🔴   File "__init__.py", line 500, in destroy

🔴 RuntimeError: Failed to disconnect signal valueChanged(QVariant).

🔴 RuntimeError: Failed to disconnect signal valueChanged(QVariant).

🔴 Note this traceback was caught by reporter and has been added to the log (Failed to disconnect signal valueChanged(QVariant).)
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 0,0,255,100.0
🟡 Clock pinned to desktop
🟢 Clock on the bottom
🟢 Clock on the right
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(2360, 1346, 200, 46)
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 0,0,255,100.0
🟡 Clock pinned to desktop
🟢 Clock on the bottom
🟡 Clock on the left
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(0, 1346, 200, 46)
🔵 Full screen rect:  (0, 0, 2560, 1440)
🟢 Custom valid shortcut specified: ['win', 'n']
🟡 Using custom font color: 255,255,255
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,50,0,0,0,0,0,Regular
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M:%S \n%A\n%d.%m.%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🟢 Custom valid shortcut specified: ['win', 'n']
🟡 Using custom font color: 255,255,255
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 373, in _parse

🔴   File "urllib\request.py", line 373, in _parse

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"')
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,50,0,0,0,0,0,Regular
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M:%S \n%A\n%d.%m.%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 373, in _parse

🔴   File "urllib\request.py", line 373, in _parse

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"')
🔵 Restart loop: 1
🔵 Version URL: https://www.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 373, in _parse

🔴   File "urllib\request.py", line 373, in _parse

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"')
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 500, in destroy

🔴   File "__init__.py", line 500, in destroy

🔴 RuntimeError: Failed to disconnect signal valueChanged(QVariant).

🔴 RuntimeError: Failed to disconnect signal valueChanged(QVariant).

🔴 Note this traceback was caught by reporter and has been added to the log (Failed to disconnect signal valueChanged(QVariant).)
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 0,0,255,100.0
🟡 Clock pinned to desktop
🟢 Clock on the bottom
🟢 Clock on the right
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(2360, 1346, 200, 46)
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 0,0,255,100.0
🟡 Clock pinned to desktop
🟢 Clock on the bottom
🟡 Clock on the left
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(0, 1346, 200, 46)
🔵 Full screen rect:  (0, 0, 2560, 1440)
🟢 Custom valid shortcut specified: ['win', 'n']
🟡 Using custom font color: 255,255,255
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,50,0,0,0,0,0,Regular
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M:%S \n%A\n%d.%m.%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🟢 Custom valid shortcut specified: ['win', 'n']
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 373, in _parse

🔴   File "urllib\request.py", line 373, in _parse

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"')
🟡 Using custom font color: 255,255,255
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,50,0,0,0,0,0,Regular
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M:%S \n%A\n%d.%m.%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 373, in _parse

🔴   File "urllib\request.py", line 373, in _parse

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"')
🔵 Restart loop: 1
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 373, in _parse

🔴   File "urllib\request.py", line 373, in _parse

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"')
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 373, in _parse

🔴   File "urllib\request.py", line 373, in _parse

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"')
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 373, in _parse

🔴   File "urllib\request.py", line 373, in _parse

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"')
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 500, in destroy

🔴   File "__init__.py", line 500, in destroy

🔴 RuntimeError: Failed to disconnect signal valueChanged(QVariant).

🔴 RuntimeError: Failed to disconnect signal valueChanged(QVariant).

🔴 Note this traceback was caught by reporter and has been added to the log (Failed to disconnect signal valueChanged(QVariant).)
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 0,0,255,100.0
🟡 Clock pinned to desktop
🟢 Clock on the bottom
🟢 Clock on the right
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(2360, 1346, 200, 46)
🔵 Full screen rect:  (0, 0, 2560, 1440)
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 0,0,255,100.0
🟡 Clock pinned to desktop
🟢 Clock on the bottom
🟡 Clock on the left
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(0, 1346, 200, 46)
🔵 Full screen rect:  (0, 0, 2560, 1440)
🟢 Custom valid shortcut specified: ['win', 'n']
🟡 Using custom font color: 255,255,255
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,50,0,0,0,0,0,Regular
🔵 Font size: 9.0
🔵 Loaded date time format: %H:%M:%S \n%A\n%d.%m.%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:True, DisableNotifications:False
🟢 Custom valid shortcut specified: ['win', 'n']
🟡 Using custom font color: 255,255,255
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,50,0,0,0,0,0,Regular
🔵 Font size: 9.0
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 373, in _parse

🔴   File "urllib\request.py", line 373, in _parse

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"')
🔵 Loaded date time format: %H:%M:%S \n%A\n%d.%m.%Y  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:True, DisableNotifications:False
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 373, in _parse

🔴   File "urllib\request.py", line 373, in _parse

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"')
🔵 Restart loop: 1
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 499, in open

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 318, in __init__

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 344, in full_url

🔴   File "urllib\request.py", line 373, in _parse

🔴   File "urllib\request.py", line 373, in _parse

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 ValueError: unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"'

🔴 Note this traceback was caught by reporter and has been added to the log (unknown url type: '# curl "http://worldtimeapi.org/api/timezone/Europe/Zurich"')
🟡 NOT showing tooltip, it has been disabled
🔵 Copying log to the clipboard...
```

**Comment by marticliment** [comment]
Pinning your clock to the desktop will make it hide when an app opens. You should disable this option to get the desired result
