### ISSUE TITLE
[BUG] (shows notification icon when viewing the desktop and the clock only whenever I am in any window)

### ISSUE THREAD

**Issue by zeruzoo** [marticliment/ElevenClock#1375]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose)).

### Describe your issue

As I previously stated: "shows notification icon when viewing the desktop and the clock only whenever I am in any window".

### Steps to reproduce the issue

I managed to figure out that if I press win+d to minimize, any window, to the desktop - then the clocks keeps on showing, but if I press the taskbar icon to minimize the window then the notification icon is the one appearing.

### ElevenClock Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.0011203289031982422 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 4.3.2 (v4.32) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "pt_BR"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1345, 818, 200, 46)
🔵 Full screen rect:  (0, 0, 1536, 864)
🔵 Using automatic font color
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,700,0,0,0,0,0,0,0,0,0,0,1,Bold
🔵 Font size: 10.0
🟡 Desktop button enabled
🔵 Loaded date time format: %H:%M  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🟢 Loaded clocks in 0.23749804496765137
🔵 Language file up-to-date
🔵 Restart loop: 1
🔵 (worldtimeapi.org) Time offset set to -2.009537935256958
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to True
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 11001] getaddrinfo failed)
🟢 Loaded everything in 1.3396985530853271
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1345, 818, 200, 46)
🔵 Full screen rect:  (0, 0, 1536, 864)
🔵 Using automatic font color
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,700,0,0,0,0,0,0,0,0,0,0,1,Bold
🔵 Font size: 10.0
🟡 Desktop button enabled
🔵 Loaded date time format: %H:%M  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🔵 Restart loop: 1
🔵 (worldtimeapi.org) Time offset set to -2.0121450424194336
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔵 (worldtimeapi.org) Time offset set to -2.010148763656616
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1345, 818, 200, 46)
🔵 Full screen rect:  (0, 0, 1536, 864)
🔵 Using automatic font color
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,700,0,0,0,0,0,0,0,0,0,0,1,Bold
🔵 Font size: 10.0
🟡 Desktop button enabled
🔵 Loaded date time format: %H:%M  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 Restart loop: 1
🔵 (worldtimeapi.org) Time offset set to -2.012838363647461
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1423, in loadInternetTimeOffset

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1423, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1377, in http_open

🔴   File "urllib\request.py", line 1377, in http_open

🔴   File "urllib\request.py", line 1352, in do_open

🔴   File "urllib\request.py", line 1352, in do_open

🔴   File "http\client.py", line 1375, in getresponse

🔴   File "http\client.py", line 1375, in getresponse

🔴   File "http\client.py", line 318, in begin

🔴   File "http\client.py", line 318, in begin

🔴   File "http\client.py", line 287, in _read_status

🔴   File "http\client.py", line 287, in _read_status

🔴 http.client.RemoteDisconnected: Remote end closed connection without response

🔴 http.client.RemoteDisconnected: Remote end closed connection without response

🔴 Note this traceback was caught by reporter and has been added to the log (Remote end closed connection without response)
🔵 Showing tooltip
🔵 Long date string: dddd, d' de 'MMMM' de 'yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, d' de 'MMMM' de 'yyyy
Action: ('win', 'n')
Action: ('win', 'n')
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1345, 818, 200, 46)
🔵 Full screen rect:  (0, 0, 1536, 864)
🔵 Using automatic font color
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,700,0,0,0,0,0,0,0,0,0,0,1,Bold
🔵 Font size: 10.0
🟡 Desktop button enabled
🔵 Loaded date time format: %H:%M  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1423, in loadInternetTimeOffset

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 1423, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1377, in http_open

🔴   File "urllib\request.py", line 1377, in http_open

🔴   File "urllib\request.py", line 1352, in do_open

🔴   File "urllib\request.py", line 1352, in do_open

🔴   File "http\client.py", line 1375, in getresponse

🔴   File "http\client.py", line 1375, in getresponse

🔴   File "http\client.py", line 318, in begin

🔴   File "http\client.py", line 318, in begin

🔴   File "http\client.py", line 287, in _read_status

🔴   File "http\client.py", line 287, in _read_status

🔴 http.client.RemoteDisconnected: Remote end closed connection without response

🔴 http.client.RemoteDisconnected: Remote end closed connection without response

🔴 Note this traceback was caught by reporter and has been added to the log (Remote end closed connection without response)
🔵 Restart loop: 1
🔵 (worldtimeapi.org) Time offset set to -2.0112500190734863
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴   File "C:\SomePrograms\ElevenClock\elevenclock_bin\__init__.py", line 100, in updateIfPossible

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 socket.gaierror: [Errno 11001] getaddrinfo failed

🔴 Note this traceback was caught by reporter and has been added to the log ([Errno 11001] getaddrinfo failed)
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1345, 818, 200, 46)
🔵 Full screen rect:  (0, 0, 1536, 864)
🔵 Using automatic font color
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,700,0,0,0,0,0,0,0,0,0,0,1,Bold
🔵 Font size: 10.0
🟡 Desktop button enabled
🔵 Loaded date time format: %H:%M  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🔵 Restart loop: 1
🔵 (worldtimeapi.org) Time offset set to -1.982347011566162
🔵 (worldtimeapi.org) Time offset set to -2.0021979808807373
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1345, 818, 200, 46)
🔵 Full screen rect:  (0, 0, 1536, 864)
🔵 Using automatic font color
🔵 Font families   : []
🔵 Custom font     : Consolas,10,-1,5,700,0,0,0,0,0,0,0,0,0,0,1,Bold
🔵 Font size: 10.0
🟡 Desktop button enabled
🔵 Loaded date time format: %H:%M  (clock 0
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🔵 Restart loop: 1
🔵 (worldtimeapi.org) Time offset set to -2.0067996978759766
🔵 (worldtimeapi.org) Time offset set to -2.0080504417419434
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔵 Showing tooltip
🔵 Long date string: dddd, d' de 'MMMM' de 'yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, d' de 'MMMM' de 'yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, d' de 'MMMM' de 'yyyy
Action: ('win', 'n')
🔵 Showing tooltip
🔵 Long date string: dddd, d' de 'MMMM' de 'yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, d' de 'MMMM' de 'yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, d' de 'MMMM' de 'yyyy
🔵 Copying log to the clipboard...
```

### Screenshots and videos

![1](https://github.com/user-attachments/assets/2fe0dc0d-bb9a-437d-a4fa-83bf6000f639)
![2](https://github.com/user-attachments/assets/98df763f-d8fe-4a76-afb0-42dfd361f66b)
![3](https://github.com/user-attachments/assets/c1fa697e-fe19-48af-84fb-2cd5d5c161a1)

**Comment by marticliment** [comment]
This is expected to be like this, pressing the taskbar gives the taskbar full focus, preventing ElevenClock to draw over it. Once the taskbar loses the focus, ElevenClock shows again
