### ISSUE TITLE
[BUG] Disappears when opening Start menu

### ISSUE THREAD

**Issue by alphaps** [marticliment/ElevenClock#1382]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose)).

### Describe your issue

It's a great piece of software, but it hides when opening Start menu (with Windows key), then shows again when closing Start menu.
(There are also other conditions/triggers for the same bug, I'll describe them if I can reproduce again easily)

__

### ElevenClock Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.00399470329284668 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 4.4.1.1 (v4.411) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1033, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🟡 Using custom font color: 170,255,0
🔵 Font families   : []
🔵 Custom font     : Segoe UI Variable,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular
🔵 Font size: 9.0
🟡 Custom loaded date time format (clock 0): %a %H:%M:%S\n%d %b wk%W.%w
🔵 Restart loop: 1
🟢 Loaded clocks in 1.1161279678344727
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 (worldtimeapi.org) Time offset set to 0.10326695442199707
🔵 Language file up-to-date
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 2.102449655532837
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1033, 200, 46)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🟡 Using custom font color: 170,255,0
🔵 Font families   : []
🔵 Custom font     : Segoe UI Variable,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular
🔵 Font size: 9.0
🟡 Custom loaded date time format (clock 0): %a %H:%M:%S\n%d %b wk%W.%w
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:True
🔵 (worldtimeapi.org) Time offset set to 0.0678868293762207
🔵 Restart loop: 1
🔵 Version URL: https://www.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "__init__.py", line 1478, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 515, in open

🔴   File "urllib\request.py", line 515, in open

🔴   File "urllib\request.py", line 532, in _open

🔴   File "urllib\request.py", line 532, in _open

🔴   File "urllib\request.py", line 492, in _call_chain

🔴   File "urllib\request.py", line 492, in _call_chain

🔴   File "urllib\request.py", line 1373, in http_open

🔴   File "urllib\request.py", line 1373, in http_open

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1428, in getresponse

🔴   File "http\client.py", line 1428, in getresponse

🔴   File "http\client.py", line 331, in begin

🔴   File "http\client.py", line 331, in begin

🔴   File "http\client.py", line 300, in _read_status

🔴   File "http\client.py", line 300, in _read_status

🔴 http.client.RemoteDisconnected: Remote end closed connection without response

🔴 http.client.RemoteDisconnected: Remote end closed connection without response

🔴 Note this traceback was caught by reporter and has been added to the log (Remote end closed connection without response)
🔵 Showing tooltip
🔵 Long date string: dddd, MMMM d, yyyy
Action: ('win', 'n')
Action: ('win', 'n')
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🔵 Copying log to the clipboard...
```

### Screenshots and videos

before: 
![image](https://github.com/user-attachments/assets/5768b7f7-cdb1-4bc6-a045-363d2e067cab)
after hitting Win key:
![image](https://github.com/user-attachments/assets/a4969ac0-73bd-47dc-8c64-394f006c7b41)

**Comment by marticliment** [comment]
I am afraid this issue is not fixable, since this is caused by the window manager giving top priority to  the taskbar when the start menu is open.
