### ISSUE TITLE
[BUG] Clicking 11clock opens notification/calendar on wrong screen (2 ext monitors)

### ISSUE THREAD

**Issue by sniemetz** [marticliment/ElevenClock#1384]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/ElevenClock/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/ElevenClock#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/ElevenClock/issues/new/choose)).

### Describe your issue

I've set 11clock to "show calendar" on click. I have the laptop screen as well as 2 external monitors. 

Expectation: A click on 11clock should open the calendar on the monitor where I clicked 11clock.

What happens: Calendar pops up on wrong screen.

### ElevenClock Log

```text
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.038604736328125 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 4.4.0 (v4.401) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 50,54,82,78.43137254901961
🟡 Custom height being used!
🟢 Clock on the bottom
invalid literal for int() with base 10: ''
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1027, 200, 30)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🟢 Custom valid shortcut specified: ['win', 'n']
🟡 Using custom font color: 255,255,255
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 8.0
🟡 Custom loaded date time format (clock 0): &nbsp; %I:%M <span style="text-transform: lowercase;">%p</span> @ %a, %b %d
🔵 Restart loop: 1
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🔵 Initializing clock 1...
🟡 Not using taskbar background color
🔵 Using bg color: 50,54,82,78.43137254901961
🟡 Custom height being used!
🟢 Clock on the bottom
invalid literal for int() with base 10: ''
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(3256, 907, 200, 30)
🔵 Full screen rect:  (1920, 0, 3456, 960)
🟢 Custom valid shortcut specified: ['win', 'n']
🟡 Using custom font color: 255,255,255
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 8.0
🟡 Custom loaded date time format (clock 1): &nbsp; %I:%M <span style="text-transform: lowercase;">%p</span> @ %a, %b %d
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🔵 Initializing clock 2...
🟡 Not using taskbar background color
🔵 Using bg color: 50,54,82,78.43137254901961
🟡 Custom height being used!
🟢 Clock on the bottom
invalid literal for int() with base 10: ''
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(-200, 1027, 200, 30)
🔵 Full screen rect:  (-1920, 0, 0, 1080)
🟢 Custom valid shortcut specified: ['win', 'n']
🟡 Using custom font color: 255,255,255
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 8.0
🟡 Custom loaded date time format (clock 2): &nbsp; %I:%M <span style="text-transform: lowercase;">%p</span> @ %a, %b %d
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🟢 Loaded clocks in 1.2888901233673096
🔵 Language file up-to-date
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1468, in loadInternetTimeOffset

🔴   File "__init__.py", line 1468, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 515, in open

🔴   File "urllib\request.py", line 515, in open

🔴   File "urllib\request.py", line 532, in _open

🔴   File "urllib\request.py", line 532, in _open

🔴   File "urllib\request.py", line 492, in _call_chain

🔴   File "urllib\request.py", line 492, in _call_chain

🔴   File "urllib\request.py", line 1373, in http_open

🔴   File "urllib\request.py", line 1373, in http_open

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1428, in getresponse

🔴   File "http\client.py", line 1428, in getresponse

🔴   File "http\client.py", line 331, in begin

🔴   File "http\client.py", line 331, in begin

🔴   File "http\client.py", line 292, in _read_status

🔴   File "http\client.py", line 292, in _read_status

🔴   File "socket.py", line 708, in readinto

🔴   File "socket.py", line 708, in readinto

🔴 ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

🔴 ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 10054] An existing connection was forcibly closed by the remote host)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1468, in loadInternetTimeOffset

🔴   File "__init__.py", line 1468, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 515, in open

🔴   File "urllib\request.py", line 515, in open

🔴   File "urllib\request.py", line 532, in _open

🔴   File "urllib\request.py", line 532, in _open

🔴   File "urllib\request.py", line 492, in _call_chain

🔴   File "urllib\request.py", line 492, in _call_chain

🔴   File "urllib\request.py", line 1373, in http_open

🔴   File "urllib\request.py", line 1373, in http_open

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1428, in getresponse

🔴   File "http\client.py", line 1428, in getresponse

🔴   File "http\client.py", line 331, in begin

🔴   File "http\client.py", line 331, in begin

🔴   File "http\client.py", line 300, in _read_status

🔴   File "http\client.py", line 300, in _read_status

🔴 http.client.RemoteDisconnected: Remote end closed connection without response

🔴 http.client.RemoteDisconnected: Remote end closed connection without response

🔴 Note this traceback was caught by reporter and has been added to the log (Remote end closed connection without response)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1468, in loadInternetTimeOffset

🔴   File "__init__.py", line 1468, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 515, in open

🔴   File "urllib\request.py", line 515, in open

🔴   File "urllib\request.py", line 532, in _open

🔴   File "urllib\request.py", line 532, in _open

🔴   File "urllib\request.py", line 492, in _call_chain

🔴   File "urllib\request.py", line 492, in _call_chain

🔴   File "urllib\request.py", line 1373, in http_open

🔴   File "urllib\request.py", line 1373, in http_open

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1428, in getresponse

🔴   File "http\client.py", line 1428, in getresponse

🔴   File "http\client.py", line 331, in begin

🔴   File "http\client.py", line 331, in begin

🔴   File "http\client.py", line 300, in _read_status

🔴   File "http\client.py", line 300, in _read_status

🔴 http.client.RemoteDisconnected: Remote end closed connection without response

🔴 http.client.RemoteDisconnected: Remote end closed connection without response

🔴 Note this traceback was caught by reporter and has been added to the log (Remote end closed connection without response)
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🟡 restartClocks function has not been defined yet!
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to True
🟢 Loaded everything in 2.9387011528015137
🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 50,54,82,78.43137254901961
🟡 Custom height being used!
🟢 Clock on the bottom
invalid literal for int() with base 10: ''
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1027, 200, 30)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Restart loop: 1
🟢 Custom valid shortcut specified: ['win', 'n']
🟡 Using custom font color: 255,255,255
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 8.0
🟡 Custom loaded date time format (clock 0): &nbsp; %I:%M <span style="text-transform: lowercase;">%p</span> @ %a, %b %d
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🔵 Initializing clock 1...
🟡 Not using taskbar background color
🔵 Using bg color: 50,54,82,78.43137254901961
🟡 Custom height being used!
🟢 Clock on the bottom
invalid literal for int() with base 10: ''
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(3256, 907, 200, 30)
🔵 Full screen rect:  (1920, 0, 3456, 960)
🟢 Custom valid shortcut specified: ['win', 'n']
🟡 Using custom font color: 255,255,255
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 8.0
🟡 Custom loaded date time format (clock 1): &nbsp; %I:%M <span style="text-transform: lowercase;">%p</span> @ %a, %b %d
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🔵 Initializing clock 2...
🟡 Not using taskbar background color
🔵 Using bg color: 50,54,82,78.43137254901961
🟡 Custom height being used!
🟢 Clock on the bottom
invalid literal for int() with base 10: ''
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🔵 Clock geometry: PySide6.QtCore.QRect(-200, 1027, 200, 30)
🔵 Full screen rect:  (-1920, 0, 0, 1080)
🟢 Custom valid shortcut specified: ['win', 'n']
🟡 Using custom font color: 255,255,255
🔵 Font families   : ['Segoe UI Variable Display Semib', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 8.0
🔵 Version URL: https://www.marticliment.com/versions/elevenclock.ver
🟡 Custom loaded date time format (clock 2): &nbsp; %I:%M <span style="text-transform: lowercase;">%p</span> @ %a, %b %d
🟢 Updates not found
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, DisableNotifications:False
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1468, in loadInternetTimeOffset

🔴   File "__init__.py", line 1468, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 515, in open

🔴   File "urllib\request.py", line 515, in open

🔴   File "urllib\request.py", line 532, in _open

🔴   File "urllib\request.py", line 532, in _open

🔴   File "urllib\request.py", line 492, in _call_chain

🔴   File "urllib\request.py", line 492, in _call_chain

🔴   File "urllib\request.py", line 1373, in http_open

🔴   File "urllib\request.py", line 1373, in http_open

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1428, in getresponse

🔴   File "http\client.py", line 1428, in getresponse

🔴   File "http\client.py", line 331, in begin

🔴   File "http\client.py", line 331, in begin

🔴   File "http\client.py", line 292, in _read_status

🔴   File "http\client.py", line 292, in _read_status

🔴   File "socket.py", line 708, in readinto

🔴   File "socket.py", line 708, in readinto

🔴 ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

🔴 ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 10054] An existing connection was forcibly closed by the remote host)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1468, in loadInternetTimeOffset

🔴   File "__init__.py", line 1468, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 515, in open

🔴   File "urllib\request.py", line 515, in open

🔴   File "urllib\request.py", line 532, in _open

🔴   File "urllib\request.py", line 532, in _open

🔴   File "urllib\request.py", line 492, in _call_chain

🔴   File "urllib\request.py", line 492, in _call_chain

🔴   File "urllib\request.py", line 1373, in http_open

🔴   File "urllib\request.py", line 1373, in http_open

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1428, in getresponse

🔴   File "http\client.py", line 1428, in getresponse

🔴   File "http\client.py", line 331, in begin

🔴   File "http\client.py", line 331, in begin

🔴   File "http\client.py", line 292, in _read_status

🔴   File "http\client.py", line 292, in _read_status

🔴   File "socket.py", line 708, in readinto

🔴   File "socket.py", line 708, in readinto

🔴 ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

🔴 ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 10054] An existing connection was forcibly closed by the remote host)
🔴 Traceback (most recent call last):

🔴 Traceback (most recent call last):

🔴   File "__init__.py", line 1468, in loadInternetTimeOffset

🔴   File "__init__.py", line 1468, in loadInternetTimeOffset

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 215, in urlopen

🔴   File "urllib\request.py", line 515, in open

🔴   File "urllib\request.py", line 515, in open

🔴   File "urllib\request.py", line 532, in _open

🔴   File "urllib\request.py", line 532, in _open

🔴   File "urllib\request.py", line 492, in _call_chain

🔴   File "urllib\request.py", line 492, in _call_chain

🔴   File "urllib\request.py", line 1373, in http_open

🔴   File "urllib\request.py", line 1373, in http_open

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "urllib\request.py", line 1348, in do_open

🔴   File "http\client.py", line 1428, in getresponse

🔴   File "http\client.py", line 1428, in getresponse

🔴   File "http\client.py", line 331, in begin

🔴   File "http\client.py", line 331, in begin

🔴   File "http\client.py", line 292, in _read_status

🔴   File "http\client.py", line 292, in _read_status

🔴   File "socket.py", line 708, in readinto

🔴   File "socket.py", line 708, in readinto

🔴 ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

🔴 ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 10054] An existing connection was forcibly closed by the remote host)
🔵 (worldtimeapi.org) Time offset set to -1.1887526512145996
🟡 NOT showing tooltip, it has been disabled
🔵 Announcement URL: https://www.marticliment.com/resources/elevenclock.announcement
🔵 Image URL: https://marticliment.com/resources/translate.png
🔵 Starting update check
🔵 Version URL: https://www.marticliment.com/versions/elevenclock.ver
🟢 Updates not found
🟡 NOT showing tooltip, it has been disabled
Action: ['win', 'n']
🔵 Saving log...
```

### Screenshots and videos

![image](https://github.com/user-attachments/assets/3a6b6f01-9267-4e73-8549-eb6d8c1b9a5e)

**Comment by marticliment** [comment]
this is a Windows 11 limitation. Notifications panel only shows on the first monitor

**Comment by sniemetz** [comment]
That's incorrect.
I can get the notification panel/calendar on the screen where I click the
little bell/alert icon - on every monitor. It fails to open in the current
screen only with 11clock.

**Comment by marticliment** [comment]
Huh, this was not possible on prior versions

**Comment by sniemetz** [comment]
It's been a while since I installed but I would have sworn that clicking on
11clock did work that way initially (but maybe I'm dreaming)

**Comment by marticliment** [comment]
No, it has never done that
